[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "helloworld"
requires-python = ">=3.9"
dependencies = [
    "hello @ git+https://github.com/PythonPackagingExample/hello@v1.1.0"
]
dynamic = ["version"]

[tool.setuptools_scm]
