name: tests

on:
    push:
    workflow_dispatch:

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Set git credentials
              run: >
                git config --global 
                url.'https://${{ secrets.PRIVATE_REPOS_READ_ACCESS_TOKEN }}@github'.insteadOf 
                https://github
            - name: "Install helloworld"
              run: "pip install ."
            - name: "Install pytest"
              run: "pip install pytest"
            - name: "Run tests"
              run: pytest tests
    manual:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Set git credentials
              run: >
                git config --global 
                url.'https://${{ secrets.PRIVATE_REPOS_READ_ACCESS_TOKEN }}@github'.insteadOf 
                https://github
            - name: "Install helloworld"
              run: "pip install ."
            - name: "Run get_helloworld"
              run: >
                python -c "from helloworld import get_helloworld;
                print(get_helloworld())"
